// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qifssjopxyfeaqgrhzkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpZnNzam9weHlmZWFxZ3JoemtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMjc1MDAsImV4cCI6MjA3MjcwMzUwMH0.IM172kGMh7PTiCFkupBd0L6NvlMb70sJOdrEXWDwdOE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});